
// Ported from refmd/packages/shared/src/configs/theme.ts

export const themeMap = {
  wechat: {
    base: {
      "color": "#333",
      "font-size": "16px",
      "line-height": "1.75",
      "letter-spacing": "0.2px",
      "font-family": "-apple-system, BlinkMacSystemFont, 'Helvetica Neue', 'PingFang SC', 'Microsoft YaHei', 'Source Han Sans SC', 'Noto Sans CJK SC', 'WenQuanYi Micro Hei', sans-serif",
    },
    inline: {
      "strong": { "font-weight": "bold" },
      "em": { "font-style": "italic" },
      "codespan": {
        "font-size": "14px",
        "color": "#e96900",
        "background": "#f8f8f8",
        "padding": "2px 4px",
        "border-radius": "4px",
        "border": "1px solid #eee",
        "margin": "0 2px",
      },
      "link": { "color": "#576b95", "text-decoration": "none", "border-bottom": "1px solid #999" },
      "wx_link": { "color": "#576b95", "text-decoration": "none" },
    },
    block: {
      "h1": { "font-size": "1.5em", "margin": "30px 0 15px", "font-weight": "bold", "text-align": "center" },
      "h2": { "font-size": "1.4em", "margin": "30px 0 15px", "font-weight": "bold", "border-bottom": "1px solid #e7e7e7", "padding-bottom": "5px" },
      "h3": { "font-size": "1.3em", "margin": "30px 0 15px", "font-weight": "bold" },
      "h4": { "font-size": "1.2em", "margin": "30px 0 15px", "font-weight": "bold" },
      "p": { "margin": "0 0 1.2em" },
      "blockquote": {
        "color": "#999",
        "padding": "10px",
        "background": "#f8f8f8",
        "border-left": "4px solid #e7e7e7",
        "margin": "20px 0",
      },
      "blockquote_p": { "margin": "0" },
      "code": { "font-size": "14px", "padding": "15px", "background": "#f8f8f8", "border-radius": "4px", "border": "1px solid #eee", "white-space": "pre-wrap", "word-wrap": "break-word" },
      "code_pre": { "margin": "20px 0" },
      "hr": { "border": "none", "border-top": "1px solid #e7e7e7", "margin": "30px 0" },
      "ul": { "margin": "0 0 20px", "padding-left": "20px" },
      "ol": { "margin": "0 0 20px", "padding-left": "20px" },
      "listitem": { "margin-bottom": "0.5em" },
      "image": { "border-radius": "4px", "display": "block", "margin": "20px auto", "max-width": "100%" },
      "figcaption": { "font-size": "14px", "color": "#999", "text-align": "center", "margin-top": "5px" },
    },
  },
  github: {
    base: {
      "color": "#333",
      "font-size": "16px",
      "line-height": "1.75",
      "letter-spacing": "0.2px",
      "font-family": "-apple-system, BlinkMacSystemFont, 'Helvetica Neue', 'PingFang SC', 'Microsoft YaHei', 'Source Han Sans SC', 'Noto Sans CJK SC', 'WenQuanYi Micro Hei', sans-serif",
    },
    inline: {
      "strong": { "font-weight": "bold" },
      "em": { "font-style": "italic" },
      "codespan": {
        "font-size": "14px",
        "color": "#e96900",
        "background": "#f8f8f8",
        "padding": "2px 4px",
        "border-radius": "4px",
        "border": "1px solid #eee",
        "margin": "0 2px",
      },
      "link": { "color": "#0366d6", "text-decoration": "none" },
    },
    block: {
      "h1": { "font-size": "2em", "margin": "0.67em 0", "font-weight": "600", "border-bottom": "1px solid #eaecef", "padding-bottom": "0.3em" },
      "h2": { "font-size": "1.5em", "margin": "0.83em 0", "font-weight": "600", "border-bottom": "1px solid #eaecef", "padding-bottom": "0.3em" },
      "h3": { "font-size": "1.25em", "margin": "1em 0", "font-weight": "600" },
      "h4": { "font-size": "1em", "margin": "1.33em 0", "font-weight": "600" },
      "p": { "margin": "0 0 16px" },
      "blockquote": {
        "color": "#6a737d",
        "padding": "0 1em",
        "border-left": "0.25em solid #dfe2e5",
        "margin": "0 0 16px",
      },
      "code": { "font-size": "14px", "padding": "16px", "background": "#f6f8fa", "border-radius": "3px", "white-space": "pre-wrap", "word-wrap": "break-word" },
      "code_pre": { "margin": "0 0 16px" },
      "hr": { "height": "0.25em", "padding": "0", "margin": "24px 0", "background-color": "#e1e4e8", "border": "0" },
      "ul": { "margin": "0 0 16px", "padding-left": "2em" },
      "ol": { "margin": "0 0 16px", "padding-left": "2em" },
      "listitem": { "margin-bottom": "0" },
      "image": { "max-width": "100%" },
      "figcaption": { "font-size": "14px", "color": "#999", "text-align": "center", "margin-top": "5px" },
    },
  },
  zinc: {
    base: {
      "color": "#3f3f46",
      "font-size": "16px",
      "line-height": "1.75",
      "letter-spacing": "0.2px",
      "font-family": "-apple-system, BlinkMacSystemFont, 'Helvetica Neue', 'PingFang SC', 'Microsoft YaHei', 'Source Han Sans SC', 'Noto Sans CJK SC', 'WenQuanYi Micro Hei', sans-serif",
    },
    inline: {
      "strong": { "font-weight": "600" },
      "em": { "font-style": "italic" },
      "codespan": {
        "font-size": "14px",
        "color": "#e96900",
        "background": "#f8f8f8",
        "padding": "2px 4px",
        "border-radius": "4px",
        "border": "1px solid #eee",
        "margin": "0 2px",
      },
      "link": { "color": "#576b95", "text-decoration": "none", "border-bottom": "1px solid #999" },
    },
    block: {
      "h1": { "font-size": "1.5em", "margin": "30px 0 15px", "font-weight": "bold", "text-align": "center" },
      "h2": { "font-size": "1.4em", "margin": "30px 0 15px", "font-weight": "bold" },
      "h3": { "font-size": "1.3em", "margin": "30px 0 15px", "font-weight": "bold" },
      "h4": { "font-size": "1.2em", "margin": "30px 0 15px", "font-weight": "bold" },
      "p": { "margin": "0 0 1.2em" },
      "blockquote": {
        "color": "#a1a1aa",
        "padding": "10px",
        "margin": "20px 0",
        "border-left": "2px solid #d4d4d8",
      },
      "blockquote_p": { "margin": "0" },
      "code": { "font-size": "14px", "padding": "15px", "background": "#f4f4f5", "border-radius": "4px", "white-space": "pre-wrap", "word-wrap": "break-word" },
      "code_pre": { "margin": "20px 0" },
      "hr": { "border": "none", "border-top": "1px solid #e7e7e7", "margin": "30px 0" },
      "ul": { "margin": "0 0 20px", "padding-left": "20px" },
      "ol": { "margin": "0 0 20px", "padding-left": "20px" },
      "listitem": { "margin-bottom": "0.5em" },
      "image": { "border-radius": "4px", "display": "block", "margin": "20px auto", "max-width": "100%" },
      "figcaption": { "font-size": "14px", "color": "#999", "text-align": "center", "margin-top": "5px" },
    },
  },
};
